# remap the prefix
unbind C-b
set -g prefix C-f

# act like vim
setw -g mode-keys vi

# Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe "reattach-to-user-namespace pbcopy"

# Update default binding of `Enter` to also use copy-pipe
unbind   -T copy-mode-vi 'Enter'
bind-key -T copy-mode-vi 'Enter' send -X copy-pipe "reattach-to-user-namespace pbcopy"

# only show constrained window if other session is active
setw -g aggressive-resize on

# shortcut to reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded."

set -g base-index 1
set -g history-limit 100000

# open new screens and panes with the current directory
bind '"' split-window -c "#{pane_current_path}"
bind %   split-window -h -c "#{pane_current_path}"
bind c   new-window -c "#{pane_current_path}"

set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm-256color:Tc'

set -g mouse on

# dynamic window name based on current directory
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'
set-option -g allow-rename on

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'dracula/tmux'
set -g @dracula-show-empty-plugins false
set -g @dracula-show-flags true
set -g @dracula-show-left-icon "#h | #S"
set -g @dracula-plugins " "

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
